#ifndef CELL_NEIGHBORS_H
#define CELL_NEIGHBORS_H

#include <godot_cpp/core/binder_common.hpp>

using namespace godot;

namespace godot {

    enum QUADRANT_NEIGHBOR {
    QUADRANT_SOUTH_WEST,
    QUADRANT_WEST,
    QUADRANT_NORTH_WEST,
    QUADRANT_NORTH,
    QUADRANT_SOUTH,
    QUADRANT_SOUTH_EAST,
    QUADRANT_EAST,
    QUADRANT_NORTH_EAST,
    QUADRANT_NEIGHBOR_MAX
    };

    enum OCTANT_NEIGHBOR {	
    OCTANT_BELOW_SOUTH_WEST,
    OCTANT_BELOW_WEST,
    OCTANT_BELOW_NORTH_WEST,
    OCTANT_BELOW_NORTH,
    OCTANT_BELOW,
    OCTANT_BELOW_SOUTH,
    OCTANT_BELOW_SOUTH_EAST,
    OCTANT_BELOW_EAST,
    OCTANT_BELOW_NORTH_EAST,
    OCTANT_SOUTH_WEST,
    OCTANT_WEST,
    OCTANT_NORTH_WEST,
    OCTANT_NORTH,
    OCTANT_SOUTH,
    OCTANT_SOUTH_EAST,
    OCTANT_EAST,
    OCTANT_NORTH_EAST,
    OCTANT_ABOVE_SOUTH_WEST,
    OCTANT_ABOVE_WEST,
    OCTANT_ABOVE_NORTH_WEST,
    OCTANT_ABOVE_NORTH,
    OCTANT_ABOVE,
    OCTANT_ABOVE_SOUTH,
    OCTANT_ABOVE_SOUTH_EAST,
    OCTANT_ABOVE_EAST,
    OCTANT_ABOVE_NORTH_EAST,
    OCTANT_NEIGHBOR_MAX
    };

    



}

VARIANT_ENUM_CAST(godot::QUADRANT_NEIGHBOR);
VARIANT_ENUM_CAST(godot::OCTANT_NEIGHBOR);

#endif